[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

# Remove the incorrect redirects that were causing issues
# Next.js handles routing internally

# Ensure no unnecessary plugins are loaded
[build.processing]
  skip_processing = false