[build]
  command = "npm run build"
  publish = ".next"
  base = "."

[build.environment]
  NODE_VERSION = "18"

# Force Netlify to use this configuration
[build.processing]
  skip_processing = false

# Ensure proper Next.js handling
[[plugins]]
  package = "@netlify/plugin-nextjs"